{{- if and .Values.persistenceClaim.enabled (not .Values.persistenceClaim.existingClaim) -}}
{{- $pvcName := include "drupal-clone.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-200" 
  labels:
    {{- include "drupal-clone.metaLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistenceClaim.memory }}
{{- end -}}
