apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  annotations:
    "helm.sh/hook-weight": "2"
spec:
  {{- if not .Values.nginx.autoscaling.enabled }} 
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      {{- with .Values.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.nginx.name }}
        tier: frontend
        track: stable
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nginx.serviceAccount.create }}
      serviceAccountName: {{ .Values.nginx.serviceAccount.name }} 
      {{- end }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.nginx.name }}
        securityContext:
          {{- toYaml .Values.nginx.securityContext | nindent 12 }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        env:
        - name: WEB_ROOT
          value: /www
        - name: PHP_SERVICE
          value: {{ .Values.nginx.environment.php.name }}
        - name: PHP_SERVICE_PORT
          value: "{{ .Values.nginx.environment.php.port }}"
        ports:
        - containerPort: {{ .Values.nginx.ports.containerPort }}
          name: {{ .Values.nginx.ports.name }}
        volumeMounts:
        - mountPath: /www
          name: {{ .Values.volume.name }}
          readOnly: false
        resources:
          {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claim.name }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
