{{- if .Values.nginx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx.serviceAccountName" . }} #Cambiar
  labels:
    {{- include "nginx.labels" . | nindent 4 }} #Cambiar
  {{- with .Values.nginx.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
