{{- if .Values.phpFpm.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.phpFpm.name }}
  labels:
    app: php-fpm
    tier: backend
    track: stable 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.phpFpm.name }} 
  minReplicas: {{ .Values.phpFpm.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.phpFpm.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.phpFpm.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.phpFpm.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.phpFpm.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.phpFpm.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
