{{- if .Values.phpFpm.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.phpFpm.name }}
  labels:
    app: php-fpm 
    tier: backend 
    track: stable
  {{- with .Values.phpFpm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
