apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpFpm.name }}
  labels:
    app: php-fpm 
    tier: backend 
    track: stable 
spec:
  #type: {{ .Values.phpFpm.service.type }}
  ports:
    - port: {{ .Values.phpFpm.service.port }}
      targetPort: {{ .Values.phpFpm.service.targetPort }}
      protocol: TCP
  selector: 
    app: {{ .Values.phpFpm.name }}
    tier: backend