apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.postInstall.migrateDrupal.name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "100"
    "helm.sh/hook-delete-policy": before-hook-creation ,hook-success
spec:
  template:
    metadata:
      name: {{ .Values.postInstall.migrateDrupal.name }}
    spec:
      containers:
      - image: "{{ .Values.postInstall.migrateDrupal.image.repository }}:{{ .Values.postInstall.migrateDrupal.image.tag }}"
        name: {{ .Values.postInstall.migrateDrupal.name }}
        command: ["/bin/bash"]
        #INSTALAR GIT EN LA IMAGEN
        args:
          - -c
          - >- 
            tar -zxf docker8-demo-site.tar.gz &&
            tar -zxf files.tar.gz &&
            mv -v files/ web/sites/default/ &&
            composer self-update --1 &&
            composer install &&
            chown -R www-data:www-data web/ && 
            cd web/ &&
            sudo -u www-data ../vendor/drush/drush/drush cr 
        imagePullPolicy: {{ .Values.postInstall.migrateDrupal.image.pullPolicy }}
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.phpFpm.environment.database.secret.name }}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.phpFpm.environment.database.secret.name }}
              key: password
        - name: DB_URL
          value: {{ .Values.phpFpm.environment.database.url }}
        - name: DB_PORT
          value: "{{ .Values.phpFpm.environment.database.port }}"
        - name: DB_NAME
          value: {{ .Values.phpFpm.environment.database.name }}
        volumeMounts:
        - mountPath: /www
          name: {{ .Values.volume.name }}
          readOnly: false
      restartPolicy: Never
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claim.name }}     