{{- $postinstallName := include "drupal-clone.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $postinstallName }}-postinstall
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "100"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
  labels:
    {{- include "drupal-clone.metaLabels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ $postinstallName }}-postinstall
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.jobs.postInstall.image.repository }}:{{ .Values.jobs.postInstall.image.tag }}"
        name: {{ $postinstallName }}-postinstall
        command: ["/bin/bash"]
        args:
          - -c
          - >-
        {{- if .Values.jobs.gitInstallation.enabled }}
            cp -a ../configmap/. web/sites/default/ &&
            tar -zxf ${ASSETS_FILENAME} &&
            rm ${ASSETS_FILENAME} &&
            mv -v files/ web/sites/default &&
            composer self-update --1 &&
            composer install &&
            cd web/ &&
            ../vendor/drush/drush/drush cr &&
            cd .. &&
            chown -R www-data:www-data web/
        {{- else }}
            tar -zxf ${ASSETS_FILENAME} &&
            tar -zxf ${CUSTOMSITE_FILENAME} &&
            rm ${ASSETS_FILENAME} && 
            rm ${CUSTOMSITE_FILENAME} &&
            mv -v files/ web/sites/default/ &&
            composer self-update --1 &&
            composer install &&
            cd web/ &&
            ../vendor/drush/drush/drush cr &&
            cd .. && 
            chown -R www-data:www-data web/ 
        {{- end }}
        imagePullPolicy: {{ .Values.jobs.postInstall.image.pullPolicy }}
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalDatabase.secretName }}
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalDatabase.secretName }}
              key: password
        - name: DB_URL
          value: {{ .Values.externalDatabase.url }}
        - name: DB_PORT
          value: "{{ .Values.externalDatabase.port }}"
        - name: DB_NAME
          value: {{ .Values.externalDatabase.name }}
        - name: ASSETS_FILENAME
          value: {{ .Values.environment.assetsFileName }}
        - name: CUSTOMSITE_FILENAME
          value: {{ .Values.environment.customSiteFileName }} 
        volumeMounts:
        - mountPath: /www
          name: drupal-storage
          readOnly: false
          {{- if .Values.jobs.gitInstallation.enabled }}
        - mountPath: /configmap
          name: settings-configmap
          {{- end }}
      restartPolicy: Never
      volumes:
        {{- if .Values.jobs.gitInstallation.enabled }}
        - name: settings-configmap
          configMap:
            name: {{ .Values.jobs.postInstall.settingsConfigMap }} 
        {{- end }}
        - name: drupal-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistenceClaim.existingClaim | default (printf "%s" (include "drupal-clone.fullname" .))  }} 
