{{- $nginxName := include "drupal-clone.fullname" . -}}
{{- $phpName := include "drupal-clone.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $nginxName }}-nginx-deployment
  annotations:
    "helm.sh/hook-weight": "2"
  labels:
    {{- include "drupal-clone.metaLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $nginxName }}-nginx
  template:
    metadata:
      labels:
        app: {{ $nginxName }}-nginx
        tier: frontend
        track: stable
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $nginxName }}-nginx
        securityContext:
          {{- toYaml .Values.nginx.securityContext | nindent 12 }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        env:
        - name: WEB_ROOT
          value: /www
        - name: PHP_SERVICE
          value: {{ $phpName }}-phpfpm-svc
        - name: PHP_SERVICE_PORT
          value: "9000"
        ports:
        - name: http
          containerPort: 80
          
        volumeMounts:
        - mountPath: /www
          name: drupal-storage
          readOnly: false
      volumes:
        - name: drupal-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistenceClaim.existingClaim | default (printf "%s" (include "drupal-clone.fullname" .))  }}
