apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.nginx.name }}
    tier: frontend
    track: stable
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.nginx.name }}
    tier: frontend