apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpFpm.name }}
  labels:
    app: {{ .Values.phpFpm.name }}
    tier: backend 
    track: stable 
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector: 
    app: {{ .Values.phpFpm.name }}
    tier: backend