{{- $phpName := include "drupal-clone.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $phpName }}-phpfpm-svc
  labels:
    app: {{ $phpName }}-phpfpm
    tier: backend 
    track: stable 
    {{- include "drupal-clone.metaLabels" . | nindent 4 }}
spec:
  ports:
    - port: 9000
      targetPort: fastcgi
      protocol: TCP
  selector: 
    app: {{ $phpName }}-phpfpm
    tier: backend
